import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedArrowleftsline11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedImagesremovebgpreview1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedSearch2line1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedMessage2line1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedGETSTARTEDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedLine30Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedArrowrightsline2Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedRectangle83Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedBelieveyoucanandyouarehalfwaythereWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedNotificationbadgeline1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedASKMEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedRectangle82Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedThisisanamazingplatformthatreallyhelpedmetomakepositive.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedSEARCHWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedRectangle84Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax5widget/generated/GeneratedMenuline1Widget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1228.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 1228.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 55, 129, 170),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1148.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 80.0,
                              child: GeneratedRectangle31Widget(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 38.0,
                              child: GeneratedRectangle30Widget(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 15.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 55.0,
                              child: GeneratedNotificationbadgeline1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 18.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 52.0,
                              child: GeneratedMenuline1Widget(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 38.0,
                              child: GeneratedSearch2line1Widget(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 36.0,
                              child: GeneratedSEARCHWidget(),
                            ),
                            Positioned(
                              left: 103.0,
                              top: 1166.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 32.0,
                              child: GeneratedASKMEWidget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 1148.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 65.0,
                              child: GeneratedMessage2line1Widget(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 264.0,
                              height: 231.0,
                              child:
                                  GeneratedBelieveyoucanandyouarehalfwaythereWidget(),
                            ),
                            Positioned(
                              left: 362.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedArrowrightsline2Widget(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 45.0,
                              child: GeneratedArrowleftsline11Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 1.0,
                              child: GeneratedLine30Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 364.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedRectangle82Widget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 386.0,
                              height: 554.0,
                              child: GeneratedRectangle83Widget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 359.0,
                              height: 364.0,
                              child:
                                  GeneratedThisisanamazingplatformthatreallyhelpedmetomakepositive(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 58.0,
                              child: GeneratedEllipse14Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 349.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 72.0,
                              child: GeneratedImagesremovebgpreview1Widget(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 844.0,
                              right: null,
                              bottom: null,
                              width: 203.0,
                              height: 44.0,
                              child: GeneratedGroup24Widget(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 1014.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 80.0,
                              child: GeneratedRectangle84Widget(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 1026.0,
                              right: null,
                              bottom: null,
                              width: 278.0,
                              height: 34.0,
                              child: GeneratedGETSTARTEDWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
