description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Offside"
      fonts: 
        - 
          asset: "fonts/Offside-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poly"
      fonts: 
        - 
          asset: "fonts/Poly-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Open Sans"
      fonts: 
        - 
          asset: "fonts/OpenSans-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Quattrocento Sans"
      fonts: 
        - 
          asset: "fonts/QuattrocentoSans-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Numans"
      fonts: 
        - 
          asset: "fonts/Numans-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Quattrocento"
      fonts: 
        - 
          asset: "fonts/Quattrocento-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Rock Salt"
      fonts: 
        - 
          asset: "fonts/RockSalt-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Oregano"
      fonts: 
        - 
          asset: "fonts/Oregano-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
