import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedDownload__2_removebgpreview12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedMenuline1Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedNotificationbadgeline4Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedDownload__2_removebgpreview11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedASKMEWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedGroup24Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedMessage2line3Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax11widget/generated/GeneratedRectangle32Widget.dart';

/* Frame iPhone 11 Pro Max - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 942.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 942.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 55, 129, 170),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 819.0,
                              child: GeneratedRectangle25Widget(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 689.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 24.653465270996094,
                              child:
                                  GeneratedDownload__2_removebgpreview12Widget(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 5.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 52.0,
                              child: GeneratedMenuline1Widget1(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 8.0,
                              child: GeneratedRectangle29Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 825.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 71.0,
                              child: GeneratedRectangle32Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup17Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup18Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 280.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup20Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 515.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup24Widget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 118.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 60.0,
                              child: GeneratedGroup21Widget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 296.0,
                              height: 58.0,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 678.0,
                              right: null,
                              bottom: null,
                              width: 279.0009765625,
                              height: 60.0,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 845.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 32.0,
                              child: GeneratedASKMEWidget1(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 55.0,
                              child: GeneratedNotificationbadgeline4Widget(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 2.0,
                              height: 3.5,
                              child:
                                  GeneratedDownload__2_removebgpreview11Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 65.0,
                              child: GeneratedMessage2line3Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
