import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedRectangle99Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedRectangle100Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedYogasunset1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedArrowleftsline17Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax20widget/generated/GeneratedRectangle97Widget.dart';

/* Frame iPhone 11 Pro Max - 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1039.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 1039.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 55, 129, 170),
                              ),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 164.0,
                              child: GeneratedRectangle97Widget(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 164.0,
                              child: GeneratedRectangle99Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 658.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 164.0,
                              child: GeneratedRectangle100Widget(),
                            ),
                            Positioned(
                              left: 167.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 247.0,
                              height: 148.0,
                              child: GeneratedGroup33Widget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 164.0,
                              child: GeneratedYogasunset1Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 70.0,
                              child: GeneratedGroup28Widget(),
                            ),
                            Positioned(
                              left: 190.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 70.0,
                              child: GeneratedGroup29Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 515.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 70.0,
                              child: GeneratedGroup30Widget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 70.0,
                              child: GeneratedGroup31Widget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 950.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 76.0,
                              child: GeneratedGroup32Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 45.0,
                              child: GeneratedArrowleftsline17Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
