import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLine39Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedRectangle85Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLine36Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLine40Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedSUBMITWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedWhatsAppImage20210626at04462Widget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedCONFIRMPASSWORDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedRamgmailcomWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedRAMWidget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedUploadpictureWidget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedEMAILIDWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLine37Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedPASSWORDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedFIRSTNAMEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLine38Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedLASTNAMEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget/generated/GeneratedSWidget.dart';

/* Frame iPhone 11 Pro Max - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 574.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: -132.0,
                top: 1309.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 621.0,
                child: GeneratedWhatsAppImage20210626at04462Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 270.0,
                child:
                    GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr2(),
              ),
              Positioned(
                left: 268.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 40.0,
                child: GeneratedUploadpictureWidget2(),
              ),
              Positioned(
                left: 14.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 44.0,
                child: GeneratedFIRSTNAMEWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 44.0,
                child: GeneratedLASTNAMEWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 44.0,
                child: GeneratedEMAILIDWidget1(),
              ),
              Positioned(
                left: 4.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 44.0,
                child: GeneratedPASSWORDWidget(),
              ),
              Positioned(
                left: -37.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 112.0,
                child: GeneratedCONFIRMPASSWORDWidget(),
              ),
              Positioned(
                left: 17.997182846069336,
                top: 411.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 1.0,
                child: GeneratedLine36Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 1.0,
                child: GeneratedLine37Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 1.0,
                child: GeneratedLine38Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 631.5,
                right: null,
                bottom: null,
                width: 355.0,
                height: 1.0,
                child: GeneratedLine39Widget(),
              ),
              Positioned(
                left: 13.983795166015625,
                top: 737.6015625,
                right: null,
                bottom: null,
                width: 355.0,
                height: 1.0,
                child: GeneratedLine40Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 784.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 64.0,
                child: GeneratedRectangle85Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 25.0,
                child: GeneratedSUBMITWidget(),
              ),
              Positioned(
                left: 235.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 19.0,
                child: GeneratedRAMWidget2(),
              ),
              Positioned(
                left: 281.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 29.0,
                child: GeneratedSWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 23.0,
                child: GeneratedRamgmailcomWidget1(),
              ),
              Positioned(
                left: 239.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 29.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 235.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 29.0,
                child: GeneratedWidget4(),
              )
            ]),
      ),
    ));
  }
}
