import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedMenuline3Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedNotificationbadgeline4Widget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedArrowleftsline13Widget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedUnionWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedHURRAYYOUHAVESUCESSFULLYJOINEDINOURTEAMFURTHERUPDATESWI.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax8widget/generated/GeneratedThumbsuplogodesignsignandsymbolgoodvector28823871remove.dart';

/* Frame iPhone 11 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 424.0,
        height: 884.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/234f69815c84c8e6d8713bad6f61096a46b3cf90.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 424.0,
                  height: 884.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 11.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 39.0,
                child: GeneratedMenuline3Widget1(),
              ),
              Positioned(
                left: 353.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 42.0,
                child: GeneratedNotificationbadgeline4Widget2(),
              ),
              Positioned(
                left: 35.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 592.0,
                child: GeneratedUnionWidget1(),
              ),
              Positioned(
                left: 84.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 322.0,
                child:
                    GeneratedHURRAYYOUHAVESUCESSFULLYJOINEDINOURTEAMFURTHERUPDATESWI(),
              ),
              Positioned(
                left: 113.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 142.0,
                child:
                    GeneratedThumbsuplogodesignsignandsymbolgoodvector28823871remove(),
              ),
              Positioned(
                left: 0.0,
                top: 816.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline13Widget2(),
              )
            ]),
      ),
    ));
  }
}
