import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedFULLNAMEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedREGISTERWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedGENDERWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedYWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedPERSONALINFORMATIONWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedNWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedCONTACTDETAILSWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedAREYOUTAKINGANYMEDICATIONSWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedAGEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedADDRESSWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedEMAILIDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedPHONENOWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedIFANYSPECIFYWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax9widget/generated/GeneratedLine16Widget.dart';

/* Frame iPhone 11 Pro Max - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 51, 136, 183),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 155.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: -75.50,
                    y: -300.50,
                    z: 0,
                    child: GeneratedFULLNAMEWidget()),
              ),
              Positioned(
                left: 134.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 30.0,
                child: GeneratedAGEWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 30.0,
                child: GeneratedGENDERWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 30.0,
                child: GeneratedADDRESSWidget(),
              ),
              Positioned(
                left: 70.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 30.0,
                child: GeneratedEMAILIDWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 833.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 57.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 37.0,
                child: GeneratedPERSONALINFORMATIONWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 37.0,
                child: GeneratedCONTACTDETAILSWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 30.0,
                child: GeneratedPHONENOWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 86.0,
                child: GeneratedAREYOUTAKINGANYMEDICATIONSWidget(),
              ),
              Positioned(
                left: 236.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 33.0,
                child: GeneratedYWidget(),
              ),
              Positioned(
                left: 317.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 33.0,
                child: GeneratedNWidget(),
              ),
              Positioned(
                left: 268.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 30.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 30.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 30.0,
                child: GeneratedIFANYSPECIFYWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 162.04937744140625,
                height: 1.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 1.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 1.0,
                child: GeneratedLine14Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 1.0,
                child: GeneratedLine15Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 1.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 162.19741821289062,
                height: 1.0,
                child: GeneratedLine17Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 1.0,
                child: GeneratedLine18Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 41.0,
                child: GeneratedREGISTERWidget(),
              )
            ]),
      ),
    ));
  }
}
