import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/Generated50Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/Generated75Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedCONFIDENCEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedMYJOURNALWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedSTRESSWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedArrowleftsline13Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedHEALTHISSUESWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/Generated30Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/Generated65Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle45Widget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedDEPRESSIONWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedMYPROGRESSWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle45Widget4.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedANXIETYWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle59Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedDownloadremovebgpreview12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRAMWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/Generated100Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax16widget/generated/GeneratedRectangle45Widget3.dart';

/* Frame iPhone 11 Pro Max - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.684341886080802e-14,
                right: null,
                bottom: null,
                width: 93.0,
                height: 105.0,
                child: GeneratedDownloadremovebgpreview12Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 36.0,
                child: GeneratedRectangle45Widget1(),
              ),
              Positioned(
                left: 153.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 32.0,
                child: GeneratedRAMWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 146.0,
                child: GeneratedRectangle45Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 63.0,
                child: GeneratedRectangle45Widget3(),
              ),
              Positioned(
                left: 24.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 63.0,
                child: GeneratedRectangle45Widget4(),
              ),
              Positioned(
                left: 45.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 27.0,
                child: GeneratedMYJOURNALWidget1(),
              ),
              Positioned(
                left: 235.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 21.0,
                child: GeneratedMYPROGRESSWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 374.0,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 374.0,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 164.0,
                child: GeneratedRectangle53Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 23.0,
                child: Generated65Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 374.0,
                child: GeneratedRectangle54Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 374.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 340.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 374.0,
                child: GeneratedRectangle56Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 258.0,
                child: GeneratedRectangle57Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 20.0,
                child: Generated30Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 20.0,
                child: Generated100Widget(),
              ),
              Positioned(
                left: 266.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 111.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 266.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 20.0,
                child: Generated75Widget(),
              ),
              Positioned(
                left: 340.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 198.0,
                child: GeneratedRectangle59Widget(),
              ),
              Positioned(
                left: 333.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 20.0,
                child: Generated50Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 60.0,
                child: GeneratedANXIETYWidget(),
              ),
              Positioned(
                left: 120.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 60.0,
                child: GeneratedSTRESSWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 60.0,
                child: GeneratedDEPRESSIONWidget(),
              ),
              Positioned(
                left: 347.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 60.0,
                child: GeneratedCONFIDENCEWidget(),
              ),
              Positioned(
                left: 279.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 56.0,
                child: GeneratedHEALTHISSUESWidget(),
              ),
              Positioned(
                left: 347.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline13Widget1(),
              )
            ]),
      ),
    ));
  }
}
