import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Line Line 31
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLine31Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 41.0,
      height: 1.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath('M0 0L41 0L41 -1L0 -1L0 0Z')
          ..color = Color.fromARGB(255, 237, 41, 41),
      ]),
    ));
  }
}
