import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedHaiRamHowcanIhelpyouWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/Generated3765854removebgpreview1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedMessage2line1Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedMessage2line2Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedTypingWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedLine50Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedLine52Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedLine53Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedArrowleftsline13Widget3.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax18widget/generated/GeneratedLine51Widget.dart';

/* Frame iPhone 11 Pro Max - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 279.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 65.0,
                child: GeneratedMessage2line1Widget1(),
              ),
              Positioned(
                left: 60.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 65.0,
                child: GeneratedMessage2line2Widget(),
              ),
              Positioned(
                left: 102.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 96.0,
                child: GeneratedHaiRamHowcanIhelpyouWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 37.0,
                child: GeneratedTypingWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 165.0,
                child: Generated3765854removebgpreview1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline13Widget3(),
              ),
              Positioned(
                left: 35.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 350.0057067871094,
                height: 1.0,
                child: GeneratedLine50Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 784.0,
                height: 1.0,
                child: GeneratedLine51Widget(),
              ),
              Positioned(
                left: 383.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 786.0025634765625,
                height: 1.0,
                child: GeneratedLine52Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 860.0,
                right: null,
                bottom: null,
                width: 350.0057067871094,
                height: 1.0,
                child: GeneratedLine53Widget(),
              )
            ]),
      ),
    ));
  }
}
