import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedDONTHAVEANACCOUNTSIGNUPWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedRectangle73Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr3.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedEXTENDYOURARMSWELCOMEYOURFUTURETHEBESTISYETTOCOMEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax2widget/generated/GeneratedGroup13Widget.dart';

/* Frame iPhone 11 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 128, 170),
                ),
              ),
              Positioned(
                left: 1.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 370.0,
                child:
                    GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr3(),
              ),
              Positioned(
                left: 46.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 94.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 87.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 115.0,
                child:
                    GeneratedEXTENDYOURARMSWELCOMEYOURFUTURETHEBESTISYETTOCOMEWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 48.0,
                child: GeneratedDONTHAVEANACCOUNTSIGNUPWidget(),
              ),
              Positioned(
                left: 307.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedRectangle73Widget(),
              )
            ]),
      ),
    ));
  }
}
