import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedUnionWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedHURRAYYOUHAVESUCESSFULLYCOMPLETEDYOURREGISTRATIONFURTHE.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedArrowleftsline12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedDownload__1_removebgpreview1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedMenuline3Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax10widget/generated/GeneratedNotificationbadgeline4Widget1.dart';

/* Frame iPhone 11 Pro Max - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 424.0,
        height: 884.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/234f69815c84c8e6d8713bad6f61096a46b3cf90.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 424.0,
                  height: 884.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 11.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 39.0,
                child: GeneratedMenuline3Widget(),
              ),
              Positioned(
                left: 353.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 42.0,
                child: GeneratedNotificationbadgeline4Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 592.0,
                child: GeneratedUnionWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 322.0,
                child:
                    GeneratedHURRAYYOUHAVESUCESSFULLYCOMPLETEDYOURREGISTRATIONFURTHE(),
              ),
              Positioned(
                left: null,
                top: 513.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 124.0,
                child: TransformHelper.translate(
                    x: 10.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDownload__1_removebgpreview1Widget()),
              ),
              Positioned(
                left: 0.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline12Widget(),
              )
            ]),
      ),
    ));
  }
}
