import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedJOINWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedPhoneWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedJOINOURTEAMWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedBusiness_Characters_Team_Work_Office_People_Corporate_E.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax7widget/generated/GeneratedRectangle46Widget.dart';

/* Frame iPhone 11 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 388.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: -26.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 465.0,
                height: 392.0,
                child:
                    GeneratedBusiness_Characters_Team_Work_Office_People_Corporate_E(),
              ),
              Positioned(
                left: 26.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 77.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 45.0,
                child: GeneratedJOINOURTEAMWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 48.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 48.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 48.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 793.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 62.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 51.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 31.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 39.0,
                child: GeneratedPhoneWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 40.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 145.0,
                top: 802.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 52.0,
                child: GeneratedJOINWidget(),
              )
            ]),
      ),
    ));
  }
}
