import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedUploadpictureWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedArrowrightsline1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedWhatsAppImage20210626at04462Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedDownloadremovebgpreview11Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax4widget/generated/GeneratedWelcomebackRamWidget.dart';

/* Frame iPhone 11 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 574.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: -132.0,
                top: 1309.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 621.0,
                child: GeneratedWhatsAppImage20210626at04462Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 270.0,
                child:
                    GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr1(),
              ),
              Positioned(
                left: 268.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 40.0,
                child: GeneratedUploadpictureWidget1(),
              ),
              Positioned(
                left: 42.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 194.0,
                child: GeneratedWelcomebackRamWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 289.0,
                child: GeneratedDownloadremovebgpreview11Widget1(),
              ),
              Positioned(
                left: 167.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 178.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 50.0,
                child: GeneratedArrowrightsline1Widget(),
              )
            ]),
      ),
    ));
  }
}
