import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedDistantnegotiationsleadbycaucasian260nw170736464521Widg.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedVidiconfill1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedDepressionatitspeakWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/Generated24Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedRecordcirclefill11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/Generated59Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedRECWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedPhonefill1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedHtmlchartpiechartsimpleexampleremovebgpreview1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedDownloadremovebgpreview22Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax13widget/generated/GeneratedRectangle79Widget.dart';

/* Frame iPhone 11 Pro Max - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProMax5Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Image.asset(
                    "assets/images/783eef19a10be4ee232699a95fea620a5082925d.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 414.0,
                    height: 896.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 799.0,
                  right: null,
                  bottom: null,
                  width: 0.0,
                  height: 19.5,
                  child: GeneratedRectangle63Widget(),
                ),
                Positioned(
                  left: 169.0,
                  top: 809.0,
                  right: null,
                  bottom: null,
                  width: 76.0,
                  height: 76.0,
                  child: GeneratedEllipse11Widget(),
                ),
                Positioned(
                  left: 182.0,
                  top: 819.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 55.0,
                  child: GeneratedPhonefill1Widget(),
                ),
                Positioned(
                  left: 73.0,
                  top: 817.0,
                  right: null,
                  bottom: null,
                  width: 66.0,
                  height: 64.0,
                  child: GeneratedEllipse12Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 820.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 62.0,
                  child: GeneratedDownloadremovebgpreview22Widget(),
                ),
                Positioned(
                  left: 270.0,
                  top: 821.0,
                  right: null,
                  bottom: null,
                  width: 60.0,
                  height: 59.0,
                  child: GeneratedEllipse13Widget(),
                ),
                Positioned(
                  left: 280.0,
                  top: 825.0,
                  right: null,
                  bottom: null,
                  width: 42.0,
                  height: 48.0,
                  child: GeneratedVidiconfill1Widget(),
                ),
                Positioned(
                  left: 300.0,
                  top: 23.0,
                  right: null,
                  bottom: null,
                  width: 113.0,
                  height: 190.0,
                  child:
                      GeneratedDistantnegotiationsleadbycaucasian260nw170736464521Widg(),
                ),
                Positioned(
                  left: 300.0,
                  top: 668.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 100.0,
                  child: GeneratedRectangle79Widget(),
                ),
                Positioned(
                  left: 16.0,
                  top: 639.0,
                  right: null,
                  bottom: null,
                  width: 270.0,
                  height: 37.0,
                  child: GeneratedGroup25Widget(),
                ),
                Positioned(
                  left: 16.0,
                  top: 692.0,
                  right: null,
                  bottom: null,
                  width: 270.0,
                  height: 41.380279541015625,
                  child: GeneratedGroup26Widget(),
                ),
                Positioned(
                  left: 16.0,
                  top: 752.0,
                  right: null,
                  bottom: null,
                  width: 270.0,
                  height: 41.380279541015625,
                  child: GeneratedGroup27Widget(),
                ),
                Positioned(
                  left: 11.0,
                  top: 11.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 24.0,
                  child: GeneratedRecordcirclefill11Widget(),
                ),
                Positioned(
                  left: 42.0,
                  top: 11.0,
                  right: null,
                  bottom: null,
                  width: 138.0,
                  height: 59.0,
                  child: GeneratedRECWidget(),
                ),
                Positioned(
                  left: 268.0,
                  top: 612.0,
                  right: null,
                  bottom: null,
                  width: 263.0,
                  height: 181.0,
                  child:
                      GeneratedHtmlchartpiechartsimpleexampleremovebgpreview1Widget(),
                ),
                Positioned(
                  left: 320.0,
                  top: 676.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 18.0,
                  child: Generated24Widget(),
                ),
                Positioned(
                  left: 371.0,
                  top: 698.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 32.0,
                  child: Generated59Widget(),
                ),
                Positioned(
                  left: 21.0,
                  top: 650.0,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 24.0,
                  child: GeneratedDepressionatitspeakWidget(),
                ),
                Positioned(
                  left: 48.0,
                  top: 686.0,
                  right: null,
                  bottom: null,
                  width: 225.0,
                  height: 20.0,
                  child: GeneratedWidget(),
                ),
                Positioned(
                  left: 39.0,
                  top: 817.0,
                  right: null,
                  bottom: null,
                  width: 243.0,
                  height: 661.0,
                  child: GeneratedWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
