import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedLine56Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle88Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedWidget6.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle91Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle94Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedDENYWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedLine54Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle96Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle95Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle93Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle90Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedJOINWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedENTERYOURMEETINGIDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle92Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedRectangle89Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedLine57Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedArrowleftsline16Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedACCEPTWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedPERMISSIONTORECORDWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedLine58Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/Generated823ffw89Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax19widget/generated/GeneratedLine55Widget.dart';

/* Frame iPhone 11 Pro Max - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 126.0,
                child: GeneratedRectangle88Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 72.0,
                child: GeneratedENTERYOURMEETINGIDWidget(),
              ),
              Positioned(
                left: 179.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 34.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 207.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 43.0,
                child: GeneratedRectangle89Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 48.0,
                child: Generated823ffw89Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 148.0,
                child: GeneratedRectangle90Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 54.0,
                child: GeneratedPERMISSIONTORECORDWidget(),
              ),
              Positioned(
                left: 195.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 25.0,
                child: GeneratedWidget6(),
              ),
              Positioned(
                left: 207.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 26.0,
                child: GeneratedRectangle91Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 26.0,
                child: GeneratedRectangle92Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 25.0,
                child: GeneratedACCEPTWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 27.0,
                child: GeneratedDENYWidget(),
              ),
              Positioned(
                left: 339.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 24.0,
                child: GeneratedRectangle93Widget(),
              ),
              Positioned(
                left: 339.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 24.0,
                child: GeneratedRectangle94Widget(),
              ),
              Positioned(
                left: 329.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 2.2360680103302,
                height: 1.0,
                child: GeneratedLine54Widget(),
              ),
              Positioned(
                left: 234.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 1.0,
                height: 1.0,
                child: GeneratedLine55Widget(),
              ),
              Positioned(
                left: 183.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 4.0,
                height: 1.0,
                child: GeneratedLine56Widget(),
              ),
              Positioned(
                left: 342.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 18.384777069091797,
                height: 1.0,
                child: GeneratedLine57Widget(),
              ),
              Positioned(
                left: 355.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 22.671567916870117,
                height: 1.0,
                child: GeneratedLine58Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 124.0,
                child: GeneratedRectangle95Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 88.0,
                child: GeneratedRectangle96Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 55.0,
                child: GeneratedJOINWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline16Widget(),
              )
            ]),
      ),
    ));
  }
}
