import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedWhatsAppImage20210626at04462Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedUploadpictureWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedMailline21Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedRamgmailcomWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedUser3line11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedBycontinuingyouagreetoourtermsofserviceprivacypolicyWid.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedKey2line1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedRamWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedCheckboxlineWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax3widget/generated/GeneratedPasswordWidget1.dart';

/* Frame iPhone 11 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 569.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCheckboxlineWidget(),
              ),
              Positioned(
                left: -132.0,
                top: 1309.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 621.0,
                child: GeneratedWhatsAppImage20210626at04462Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 270.0,
                child:
                    GeneratedYoung_Woman_Getting_Help_And_Cure_From_Stressremovebgpr(),
              ),
              Positioned(
                left: 170.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 69.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 40.0,
                child: GeneratedUploadpictureWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 73.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 20.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 66.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailline21Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 322.0006408691406,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 47.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 138.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 33.0,
                child: GeneratedRamgmailcomWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 28.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: -18.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 21.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: -18.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 21.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 66.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUser3line11Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedKey2line1Widget(),
              ),
              Positioned(
                left: 83.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 40.0,
                child: GeneratedRamWidget(),
              ),
              Positioned(
                left: 82.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 43.0,
                child:
                    GeneratedBycontinuingyouagreetoourtermsofserviceprivacypolicyWid(),
              )
            ]),
      ),
    ));
  }
}
