import 'package:flutter/material.dart';

/* Vector Ellipse 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 17.0,
      height: 8.5,
    ));
  }
}
