import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRAMWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedDay2Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedDay1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedArrowleftsline14Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedMYPROGRESSWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedMYJOURNALWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedDownloadremovebgpreview11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax15widget/generated/GeneratedRectangle36Widget.dart';

/* Frame iPhone 11 Pro Max - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 105.0,
                child: GeneratedDownloadremovebgpreview11Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 36.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 32.0,
                child: GeneratedRAMWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 146.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 63.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 223.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 63.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 27.0,
                child: GeneratedMYJOURNALWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 21.0,
                child: GeneratedMYPROGRESSWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 31.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 31.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 17.0,
                child: GeneratedDay1Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 138.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 138.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 32.0,
                child: GeneratedDay2Widget(),
              ),
              Positioned(
                left: 350.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline14Widget(),
              )
            ]),
      ),
    ));
  }
}
