import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedGloballine1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedENGLISHWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine47Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedHINDIWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedArrowleftsline15Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine48Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedMARATHIWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine42Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLANGUAGEWidget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine41Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine44Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedRectangle85Widget1.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine46Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine43Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine45Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedRectangle86Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedMALAYALAMWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedSPANISHWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedLine49Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedCHINEESEWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedFRENCHWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedDUTCHWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax17widget1/generated/GeneratedPORTUGESEWidget.dart';

/* Frame iPhone 11 Pro Max - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax17Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 70.0,
                child: GeneratedRectangle85Widget1(),
              ),
              Positioned(
                left: 116.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 33.0,
                child: GeneratedLANGUAGEWidget1(),
              ),
              Positioned(
                left: 91.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGloballine1Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 758.0,
                child: GeneratedRectangle86Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine41Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine45Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine42Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 808.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine48Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine49Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine46Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 290.00689697265625,
                height: 1.0,
                child: GeneratedLine47Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 1.0,
                child: GeneratedLine43Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 1.0,
                child: GeneratedLine44Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 29.0,
                child: GeneratedENGLISHWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 29.0,
                child: GeneratedMALAYALAMWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 29.0,
                child: GeneratedHINDIWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 29.0,
                child: GeneratedMARATHIWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 29.0,
                child: GeneratedFRENCHWidget(),
              ),
              Positioned(
                left: 154.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 29.0,
                child: GeneratedDUTCHWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 29.0,
                child: GeneratedPORTUGESEWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 40.0,
                child: GeneratedSPANISHWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 29.0,
                child: GeneratedCHINEESEWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedArrowleftsline15Widget(),
              )
            ]),
      ),
    ));
  }
}
