import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedUnionWidget2.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedCLICKTOJOINTHEMEETINGMEETINGID823ffw89Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedHiiRamIamDrAgnusPshychiatristsatMountHillHospitalIamyou.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedUnionWidget3.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedRectangle87Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax12widget/generated/GeneratedLine29Widget.dart';

/* Frame iPhone 11 Pro Max - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProMax5Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 55, 129, 170),
                  ),
                ),
                Positioned(
                  left: 9.0,
                  top: 21.0,
                  right: null,
                  bottom: null,
                  width: 399.0003356933594,
                  height: 83.89739227294922,
                  child: GeneratedGroup16Widget(),
                ),
                Positioned(
                  left: 41.0,
                  top: 93.0,
                  right: null,
                  bottom: null,
                  width: 386.0013122558594,
                  height: 1.0,
                  child: GeneratedLine29Widget(),
                ),
                Positioned(
                  left: 23.0,
                  top: 120.0,
                  right: null,
                  bottom: null,
                  width: 354.0,
                  height: 408.7954406738281,
                  child: GeneratedUnionWidget2(),
                ),
                Positioned(
                  left: 23.0,
                  top: 184.0,
                  right: null,
                  bottom: null,
                  width: 344.0,
                  height: 320.0,
                  child:
                      GeneratedHiiRamIamDrAgnusPshychiatristsatMountHillHospitalIamyou(),
                ),
                Positioned(
                  left: 27.0,
                  top: 546.0,
                  right: null,
                  bottom: null,
                  width: 354.0,
                  height: 293.4942626953125,
                  child: GeneratedUnionWidget3(),
                ),
                Positioned(
                  left: 67.0,
                  top: 650.0,
                  right: null,
                  bottom: null,
                  width: 274.0,
                  height: 157.0,
                  child: GeneratedRectangle87Widget(),
                ),
                Positioned(
                  left: 72.0,
                  top: 693.0,
                  right: null,
                  bottom: null,
                  width: 265.0,
                  height: 116.0,
                  child:
                      GeneratedCLICKTOJOINTHEMEETINGMEETINGID823ffw89Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
