import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedDownloadVideocallingWithTherapistConceptforfree1Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedWEAREHERETOPROVIDEYOUWITHAONESTOPSOLUTIONFORANXIETYDEPR.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedArrowleftsline13Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax14widget/generated/GeneratedABOUTWidget.dart';

/* Frame iPhone 11 Pro Max - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProMax11Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 55, 129, 170),
                  ),
                ),
                Positioned(
                  left: 112.0,
                  top: -25.0,
                  right: null,
                  bottom: null,
                  width: 196.0,
                  height: 157.0,
                  child: GeneratedABOUTWidget(),
                ),
                Positioned(
                  left: 116.0,
                  top: 95.0,
                  right: null,
                  bottom: null,
                  width: 182.0,
                  height: 1.0,
                  child: GeneratedLine19Widget(),
                ),
                Positioned(
                  left: 61.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 325.0,
                  height: 257.0,
                  child:
                      GeneratedDownloadVideocallingWithTherapistConceptforfree1Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 386.0,
                  right: null,
                  bottom: null,
                  width: 419.0,
                  height: 492.0,
                  child: GeneratedRectangle45Widget(),
                ),
                Positioned(
                  left: 48.0,
                  top: 406.0,
                  right: null,
                  bottom: null,
                  width: 354.0,
                  height: 453.0,
                  child:
                      GeneratedWEAREHERETOPROVIDEYOUWITHAONESTOPSOLUTIONFORANXIETYDEPR(),
                ),
                Positioned(
                  left: 13.0,
                  top: 29.0,
                  right: null,
                  bottom: null,
                  width: 48.0,
                  height: 45.0,
                  child: GeneratedArrowleftsline13Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
