import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedLine33Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedNotificationbadgeline3Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedLine34Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedRectangle80Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedOnline_Psychology_Help__Illustration_Psychotherapy_For_.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedLine35Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedREGISTERFORCOUNCELLINGWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedJOINTHETEAMWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedRectangle81Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax6widget/generated/GeneratedMenuline2Widget.dart';

/* Frame iPhone 11 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 55, 129, 170),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 94.0,
                child: GeneratedRectangle80Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 94.0,
                child: GeneratedRectangle81Widget(),
              ),
              Positioned(
                left: -5.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 428.0,
                child:
                    GeneratedOnline_Psychology_Help__Illustration_Psychotherapy_For_(),
              ),
              Positioned(
                left: 180.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 39.0,
                child: GeneratedORWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 39.0,
                child: GeneratedMenuline2Widget(),
              ),
              Positioned(
                left: 354.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 42.0,
                child: GeneratedNotificationbadgeline3Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 131.9956817626953,
                height: 1.0,
                child: GeneratedLine32Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 1.0,
                child: GeneratedLine33Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 50.0,
                child: GeneratedJOINTHETEAMWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 60.0,
                child: GeneratedREGISTERFORCOUNCELLINGWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 361.0055236816406,
                height: 1.0,
                child: GeneratedLine34Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 870.0,
                right: null,
                bottom: null,
                width: 346.01300048828125,
                height: 1.0,
                child: GeneratedLine35Widget(),
              )
            ]),
      ),
    ));
  }
}
