import 'package:flutter/material.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax1widget/generated/GeneratedPsychologist_logoremovebgpreview11Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax1widget/generated/GeneratedTHECOUNCELLINGAPPWidget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax1widget/generated/GeneratedWhatsAppImage20210626at04461Widget.dart';
import 'package:flutterapp/heal_the_20counceling_20appapp/generatediphone11promax1widget/generated/GeneratedHEALWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProMax2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Image.asset(
                    "assets/images/312fff85e7c43eae66e0ecad52316306704c0596.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 414.0,
                    height: 896.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 57.0,
                  top: 198.0,
                  right: null,
                  bottom: null,
                  width: 300.0,
                  height: 279.0,
                  child: GeneratedPsychologist_logoremovebgpreview11Widget(),
                ),
                Positioned(
                  left: -298.0,
                  top: 493.0,
                  right: null,
                  bottom: null,
                  width: 640.0,
                  height: 856.0,
                  child: GeneratedWhatsAppImage20210626at04461Widget(),
                ),
                Positioned(
                  left: null,
                  top: 564.0,
                  right: null,
                  bottom: null,
                  width: 286.0000915527344,
                  height: 60.00001907348633,
                  child: TransformHelper.translate(
                      x: 9.00,
                      y: 0.00,
                      z: 0,
                      child: GeneratedTHECOUNCELLINGAPPWidget()),
                ),
                Positioned(
                  left: 42.0,
                  top: 470.0,
                  right: null,
                  bottom: null,
                  width: 348.0,
                  height: 96.0,
                  child: GeneratedHEALWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
